const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const clubs=[
 {name:'Northbridge United',level:72,league:'Premier Division',style:'Possession',wage:18000},
 {name:'Riverside Athletic',level:67,league:'Championship',style:'Counter',wage:11000},
 {name:'Capital City',level:80,league:'Premier Division',style:'High press',wage:32000},
 {name:'Royal Madrid CF',level:88,league:'Liga España',style:'Possession',wage:70000},
 {name:'Milano Rossoneri',level:82,league:'Serie Italia',style:'Direct',wage:42000},
 {name:'Rotterdam 1908',level:76,league:'Eredivisie',style:'Youth',wage:23000},
 {name:'Lisboa Verde',level:78,league:'Liga Portugal',style:'Technical',wage:25000}
];
const base={started:false,first:'Jayden',last:'Cole',nationality:'England',position:'LW',foot:'Right',height:175,path:'Academy graduate',difficulty:'Professional',age:17,club:'South London FC',overall:64,potential:82,value:1.2,wage:4200,trust:55,form:6.7,apps:0,goals:0,assists:0,week:1,season:1,training:3,attributes:{pace:72,shooting:58,passing:61,dribbling:70,physical:54,defending:35},timeline:['Signed first professional contract at South London FC.'],news:['Local academy graduate tipped for first-team minutes this season.'],interests:[],offers:[],agentIntent:'balanced'};
let S=JSON.parse(localStorage.getItem('rtgCareer')||'null')||structuredClone(base);
function save(){localStorage.setItem('rtgCareer',JSON.stringify(S)); flash('Career saved.');}
function flash(t){$('#matchMessage').textContent=t}
function money(v){return v>=1?`£${v.toFixed(v<10?1:0)}m`:`£${Math.round(v*1000)}k`}
function render(){
 $('#creator').classList.toggle('hidden',S.started); $('#career').classList.toggle('hidden',!S.started); if(!S.started)return;
 $('#playerName').textContent=`${S.first} ${S.last}`; $('#clubName').textContent=S.club; $('#posText').textContent=S.position; $('#nationText').textContent=S.nationality; $('#ageText').textContent=`${S.age} yrs`; $('#ovr').textContent=S.overall; $('#pot').textContent=S.potential; $('#value').textContent=money(S.value); $('#trust').textContent=S.trust; $('#trustBar').style.width=S.trust+'%'; $('#form').textContent=S.form.toFixed(1); $('#apps').textContent=S.apps; $('#goals').textContent=S.goals; $('#assists').textContent=S.assists; $('#week').textContent=S.week; $('#avatar').textContent=S.position==='ST'?'9':S.position.includes('W')?'11':'10';
 $('#managerNote').textContent=S.trust>80?'You are one of the first names on the team sheet.':S.trust>60?'You are pushing hard for a regular starting place.':S.trust>40?'You are in the rotation. Earn your place.':'Your place in the squad is under pressure.';
 $('#timeline').innerHTML=S.timeline.map((x,i)=>`<div><small>Season ${S.season} · Week ${Math.max(1,S.week-i*2)}</small><p>${x}</p></div>`).join('');
 $('#attributes').innerHTML=Object.entries(S.attributes).map(([k,v])=>`<div class="attr"><span>${k[0].toUpperCase()+k.slice(1)}</span><b>${v}</b></div>`).join('');
 renderTransfers(); renderNews();
}
function renderTransfers(){
 if(!S.interests.length) generateInterest();
 $('#interestList').innerHTML=S.interests.map(x=>`<div class="interest-card"><div><b>${x.club}</b><div>${x.league}</div></div><em>${x.stage}</em></div>`).join('');
 $('#offers').innerHTML=S.offers.length?S.offers.map((o,i)=>`<div class="offer-card"><div><b>${o.club}</b><p>${o.role} · £${o.wage.toLocaleString()}/week · ${o.years} years</p></div><div class="offer-actions"><button onclick="acceptOffer(${i})" class="primary">Accept</button><button onclick="rejectOffer(${i})">Reject</button></div></div>`).join(''):'<div class="message">No formal offers yet. Strong form creates better opportunities.</div>';
}
function generateInterest(){
 const candidates=clubs.filter(c=>c.name!==S.club).sort(()=>Math.random()-.5).slice(0,3);
 S.interests=candidates.map(c=>{let gap=c.level-S.overall; let stage=gap>18?'Monitoring':gap>10?'Scouting':gap>4?'Strong Interest':'Agent Contact'; if(S.form>7.5&&gap<14)stage='Strong Interest'; return {club:c.name,league:c.league,stage,level:c.level,wage:c.wage};});
}
window.acceptOffer=i=>{const o=S.offers[i]; S.club=o.club; S.wage=o.wage; S.trust=48; S.timeline.unshift(`Completed a transfer to ${o.club} and signed a ${o.years}-year contract.`); S.news.unshift(`${S.first} ${S.last} completes move to ${o.club}.`); S.offers=[]; S.interests=[]; save(); render();};
window.rejectOffer=i=>{S.news.unshift(`${S.first} ${S.last} rejects an approach from ${S.offers[i].club}.`);S.offers.splice(i,1);save();render();};
function renderNews(){ $('#newsFeed').innerHTML=S.news.slice(0,14).map((n,i)=>`<div class="news-item"><small>Week ${Math.max(1,S.week-i)}</small><h4>${n}</h4><p>${i===0?'The story is developing across the football world.':'Fans are discussing what this could mean for the player’s career.'}</p></div>`).join(''); }
$('#startBtn').onclick=()=>{S=structuredClone(base);S.started=true;S.first=$('#firstName').value||'Player';S.last=$('#lastName').value||'One';S.nationality=$('#nationality').value;S.position=$('#position').value;S.foot=$('#foot').value;S.height=+$('#height').value;S.path=$('#path').value;S.difficulty=$('#difficulty').value;if(S.path==='Highly rated wonderkid'){S.overall=69;S.potential=88;S.value=3.8}else if(S.path==='Lower-league prospect'){S.overall=61;S.potential=79;S.club='Borough Town';S.value=.55}else if(S.path==='Released academy player'){S.overall=60;S.potential=80;S.club='Eastside Rovers';S.value=.35}S.timeline=[`${S.path}: joined the senior squad at ${S.club}.`];S.news=[`${S.first} ${S.last}, ${S.age}, begins a professional career at ${S.club}.`];save();render();};
$('#saveBtn').onclick=save; $('#resetBtn').onclick=()=>{if(confirm('Reset this career?')){localStorage.removeItem('rtgCareer');S=structuredClone(base);render();}};
$$('.tab').forEach(b=>b.onclick=()=>{$$('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.tab-page').forEach(p=>p.classList.add('hidden'));$('#'+b.dataset.tab).classList.remove('hidden')});
$$('[data-agent]').forEach(b=>b.onclick=()=>{S.agentIntent=b.dataset.agent;const texts={bigger:'I’ll prioritise ambitious clubs, but they will expect your performances to justify the move.',minutes:'I’ll look for clubs where you can realistically start most weeks.',loan:'I’ll target loans where your position is genuinely needed.',stay:'Understood. I’ll focus on your contract and development here.'};$('#agentText').textContent=texts[b.dataset.agent];S.interests=[];generateInterest();save();renderTransfers();});
$$('[data-train]').forEach(b=>b.onclick=()=>{if(S.training<=0){$('#trainingMsg').textContent='No sessions left this week.';return}let k=b.dataset.train;S.training--;let gain=Math.random()<.3?2:1;S.attributes[k]=Math.min(99,S.attributes[k]+gain);let avg=Object.values(S.attributes).reduce((a,b)=>a+b,0)/6; if(avg>S.overall-3&&Math.random()<.35){S.overall++;S.value*=1.13;S.news.unshift(`${S.first} ${S.last}'s development is turning heads after another strong training block.`)} $('#trainingMsg').textContent=`${k[0].toUpperCase()+k.slice(1)} improved by ${gain}. ${S.training} sessions left.`;save();render();});

const cvs=$('#gameCanvas'),ctx=cvs.getContext('2d'); let match=null,keys={};
addEventListener('keydown',e=>{keys[e.key.toLowerCase()]=true;if(e.key.toLowerCase()==='c'){let s=$('#cameraSelect'),i=(s.selectedIndex+1)%s.options.length;s.selectedIndex=i;}if(e.code==='Space') e.preventDefault()}); addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);
function startMatch(){
 match={running:true,time:0,home:0,away:0,rating:6,poss:false,chances:0,dribbles:0,player:{x:280,y:310,vx:0,vy:0},ball:{x:550,y:310,vx:0,vy:0,owner:null},mates:[],foes:[]};
 for(let i=0;i<9;i++)match.mates.push({x:120+Math.random()*420,y:65+Math.random()*490}); for(let i=0;i<10;i++)match.foes.push({x:580+Math.random()*390,y:65+Math.random()*490});
 $('#kickoffBtn').textContent='Restart Match'; $('#matchMessage').textContent='Match live. Get into good positions and call for the ball.'; requestAnimationFrame(loop)
}
$('#kickoffBtn').onclick=startMatch;
$('#simBtn').onclick=()=>finishSim();
function finishSim(){let perf=Math.max(5.3,Math.min(9.6,6.2+(Math.random()*2.2)+(S.overall-64)/35));let g=Math.random()<Math.max(.08,(perf-6)/4)?1:0;let a=Math.random()<Math.max(.09,(perf-6)/3.7)?1:0;completeMatch(perf,g,a,Math.random()<.48?1:0,Math.random()<.42?1:0)}
function completeMatch(perf,g,a,hs,as){S.apps++;S.goals+=g;S.assists+=a;S.form=+(S.form*.62+perf*.38).toFixed(1);S.trust=Math.max(0,Math.min(100,S.trust+Math.round((perf-6.5)*3)+g*3+a*2));S.week++;S.training=3;if(S.week%8===0&&S.age<23&&S.form>7.1){S.overall=Math.min(S.potential,S.overall+1);S.value*=1.1}if(S.week%52===0){S.age++;S.season++;S.week=1}let headline=perf>=8?`${S.first} ${S.last} stars in an excellent ${perf.toFixed(1)} performance.`:perf<6?`${S.first} ${S.last} faces questions after a difficult outing.`:`${S.first} ${S.last} posts a ${perf.toFixed(1)} match rating.`;S.news.unshift(headline); if(perf>7.6)S.timeline.unshift(`Delivered a standout ${perf.toFixed(1)} performance for ${S.club}.`);transferTick(perf);save();render();$('#matchRating').textContent=perf.toFixed(1);$('#homeScore').textContent=hs;$('#awayScore').textContent=as;$('#matchMessage').textContent=`Full-time. Rating ${perf.toFixed(1)}${g?` · ${g} goal`:''}${a?` · ${a} assist`:''}.`}
function transferTick(perf){S.interests=[];generateInterest();if(perf>7.5||S.form>7.4){let possible=S.interests.filter(x=>x.stage==='Strong Interest'||x.stage==='Agent Contact');if(possible.length&&Math.random()<.48){let x=possible[Math.floor(Math.random()*possible.length)];let role=x.level>S.overall+8?'Prospect':'Rotation';if(S.agentIntent==='minutes')role='Important';S.offers.push({club:x.club,wage:Math.round(x.wage*(.8+Math.random()*.45)),years:3+Math.floor(Math.random()*3),role});S.news.unshift(`${x.club} submit a formal contract proposal for ${S.first} ${S.last}.`)}}
}
function loop(){if(!match?.running)return;update();draw(); if(match.time>=90*60){match.running=false;let g=match.home, a=match.away;completeMatch(match.rating,match.playerGoals||0,match.playerAssists||0,g,a);return}requestAnimationFrame(loop)}
function update(){let p=match.player,spd=keys.shift?3.35:2.35,dx=(keys.d||keys.arrowright?1:0)-(keys.a||keys.arrowleft?1:0),dy=(keys.s||keys.arrowdown?1:0)-(keys.w||keys.arrowup?1:0),m=Math.hypot(dx,dy)||1;p.x=Math.max(25,Math.min(1075,p.x+dx/m*spd));p.y=Math.max(25,Math.min(595,p.y+dy/m*spd));match.time+=.038*60; let b=match.ball;
 let dist=Math.hypot(p.x-b.x,p.y-b.y); if(dist<22&&b.owner===null){b.owner='player';match.poss=true;match.rating=Math.min(10,match.rating+.02)} if(b.owner==='player'){b.x=p.x+12;b.y=p.y;if(keys.j){keys.j=false;let goalY=310+(Math.random()-.5)*90;let quality=Math.max(.05,1-Math.hypot(1040-p.x,goalY-p.y)/900);if(Math.random()<quality*.42){match.home++;match.playerGoals=(match.playerGoals||0)+1;match.rating=Math.min(10,match.rating+1.25);flash('GOAL! Huge moment.')}else{flash('Shot saved or wide.')}b.owner=null;b.x=650;b.y=310}if(keys[' ']){keys[' ']=false;b.owner=null;b.vx=5;b.vy=(Math.random()-.5)*2;match.chances++;match.rating=Math.min(10,match.rating+.12)}}else{b.x+=b.vx||((Math.random()-.5)*.35);b.y+=b.vy||((Math.random()-.5)*.35);b.vx*=.985;b.vy*=.985;if(Math.random()<.003){b.x=150+Math.random()*760;b.y=60+Math.random()*500}}
 match.foes.forEach((f,i)=>{let tx=i<4?b.x:620,ty=i<4?b.y:80+i*120;f.x+=(tx-f.x)*.002;f.y+=(ty-f.y)*.002;if(b.owner==='player'&&Math.hypot(f.x-p.x,f.y-p.y)<19&&Math.random()<.02){b.owner=null;match.rating=Math.max(3,match.rating-.08);flash('Possession lost.')} });
 match.mates.forEach((a,i)=>{a.x+=(Math.min(1020,b.x-40+(i%3)*30)-a.x)*.0015;a.y+=(80+(i%5)*105-a.y)*.0012});
 $('#clock').textContent=`${String(Math.min(90,Math.floor(match.time/60))).padStart(2,'0')}:${String(Math.floor(match.time%60)).padStart(2,'0')}`;$('#homeScore').textContent=match.home;$('#awayScore').textContent=match.away;$('#matchRating').textContent=match.rating.toFixed(1)
}
function draw(){let mode=$('#cameraSelect').value,p=match.player,scale=1,ox=0,oy=0;if(mode==='Pro Camera'){scale=1.42;ox=cvs.width/2-p.x*scale;oy=cvs.height*.68-p.y*scale}else if(mode==='Shoulder'){scale=1.72;ox=cvs.width*.42-p.x*scale;oy=cvs.height*.72-p.y*scale}else if(mode==='Player Follow'){scale=1.2;ox=cvs.width/2-p.x*scale;oy=cvs.height/2-p.y*scale}else{scale=1;}
 ctx.save();ctx.clearRect(0,0,cvs.width,cvs.height);ctx.translate(ox,oy);ctx.scale(scale,scale);drawPitch();match.mates.forEach(x=>drawPlayer(x,'#8be6ff'));match.foes.forEach(x=>drawPlayer(x,'#ff6f78'));drawPlayer(p,'#f1ff51',true);ctx.beginPath();ctx.arc(match.ball.x,match.ball.y,7,0,Math.PI*2);ctx.fillStyle='#fff';ctx.fill();ctx.strokeStyle='#222';ctx.stroke();ctx.restore();}
function drawPitch(){ctx.fillStyle='#16733a';ctx.fillRect(0,0,1100,620);for(let i=0;i<10;i++){ctx.fillStyle=i%2?'rgba(255,255,255,.025)':'rgba(0,0,0,.025)';ctx.fillRect(i*110,0,110,620)}ctx.strokeStyle='rgba(255,255,255,.8)';ctx.lineWidth=3;ctx.strokeRect(18,18,1064,584);ctx.beginPath();ctx.moveTo(550,18);ctx.lineTo(550,602);ctx.stroke();ctx.beginPath();ctx.arc(550,310,78,0,Math.PI*2);ctx.stroke();ctx.strokeRect(18,155,175,310);ctx.strokeRect(907,155,175,310);ctx.strokeRect(18,230,70,160);ctx.strokeRect(1012,230,70,160)}
function drawPlayer(x,c,hero=false){ctx.beginPath();ctx.arc(x.x,x.y,hero?12:10,0,Math.PI*2);ctx.fillStyle=c;ctx.fill();if(hero){ctx.strokeStyle='#fff';ctx.lineWidth=3;ctx.stroke();ctx.fillStyle='#fff';ctx.font='bold 12px sans-serif';ctx.fillText(S.first.toUpperCase(),x.x-26,x.y-18)}}
$('#cameraSelect').onchange=()=>flash(`Camera changed to ${$('#cameraSelect').value}.`);
render();