import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.186.0/build/three.module.js';

const wrap=document.querySelector('.pitch-wrap'),legacyCanvas=document.getElementById('gameCanvas');
if(!wrap||!legacyCanvas)throw new Error('3D match container not found');
const bridge=()=>window.Career3DBridge||{};const getMatch=()=>bridge().getMatch?.()||null;
legacyCanvas.style.opacity='0';legacyCanvas.style.pointerEvents='none';legacyCanvas.style.position='relative';legacyCanvas.style.zIndex='0';

const scene=new THREE.Scene();scene.background=new THREE.Color(0x9dc9e8);scene.fog=new THREE.Fog(0x9dc9e8,72,155);
const camera=new THREE.PerspectiveCamera(50,16/9,.1,250);
const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.5));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.domElement.id='threeGameCanvas';Object.assign(renderer.domElement.style,{position:'absolute',inset:'0',width:'100%',height:'100%',zIndex:'1',borderRadius:'15px',touchAction:'none'});wrap.insertBefore(renderer.domElement,document.getElementById('touchControls'));const touch=document.getElementById('touchControls');if(touch)touch.style.zIndex='5';
scene.add(new THREE.HemisphereLight(0xffffff,0x4d6b35,2.1));const sun=new THREE.DirectionalLight(0xffffff,3);sun.position.set(-35,55,25);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-75;sun.shadow.camera.right=75;sun.shadow.camera.top=55;sun.shadow.camera.bottom=-55;scene.add(sun);

const FIELD_L=105,FIELD_W=68;const pitch=new THREE.Mesh(new THREE.PlaneGeometry(FIELD_L,FIELD_W),new THREE.MeshStandardMaterial({color:0x2b8a45,roughness:.95}));pitch.rotation.x=-Math.PI/2;pitch.receiveShadow=true;scene.add(pitch);
for(let i=0;i<10;i++)if(i%2===0){const s=new THREE.Mesh(new THREE.PlaneGeometry(FIELD_L/10-.05,FIELD_W),new THREE.MeshBasicMaterial({color:0xffffff,transparent:true,opacity:.025,depthWrite:false}));s.rotation.x=-Math.PI/2;s.position.set(-FIELD_L/2+(i+.5)*FIELD_L/10,.012,0);scene.add(s);}
const lineMat=new THREE.LineBasicMaterial({color:0xffffff,transparent:true,opacity:.95});function line(points){scene.add(new THREE.Line(new THREE.BufferGeometry().setFromPoints(points.map(p=>new THREE.Vector3(p[0],.035,p[1]))),lineMat));}
line([[-52.5,-34],[52.5,-34],[52.5,34],[-52.5,34],[-52.5,-34]]);line([[0,-34],[0,34]]);function rectLine(x1,z1,x2,z2){line([[x1,z1],[x2,z1],[x2,z2],[x1,z2],[x1,z1]])}rectLine(-52.5,-20.16,-36,20.16);rectLine(36,-20.16,52.5,20.16);rectLine(-52.5,-9.16,-47,9.16);rectLine(47,-9.16,52.5,9.16);const cc=[];for(let i=0;i<=64;i++){const a=i/64*Math.PI*2;cc.push([Math.cos(a)*9.15,Math.sin(a)*9.15])}line(cc);
const standMat=new THREE.MeshStandardMaterial({color:0x253342,roughness:.8}),crowdMat=new THREE.MeshStandardMaterial({color:0x51616e,roughness:.9});function stand(x,z,w,d){const b=new THREE.Mesh(new THREE.BoxGeometry(w,7,d),standMat);b.position.set(x,3.5,z);scene.add(b);const c=new THREE.Mesh(new THREE.BoxGeometry(w*.96,2.5,d*.75),crowdMat);c.position.set(x,7.1,z);scene.add(c)}stand(0,-43,112,12);stand(0,43,112,12);stand(-61,0,12,74);stand(61,0,12,74);
const boardMat=new THREE.MeshStandardMaterial({color:0x101b22,emissive:0x07100b,emissiveIntensity:.4});[[-54.5,0,.35,68],[54.5,0,.35,68],[0,-35.5,105,.35],[0,35.5,105,.35]].forEach(([x,z,w,d])=>{const m=new THREE.Mesh(new THREE.BoxGeometry(w,1.1,d),boardMat);m.position.set(x,.55,z);scene.add(m)});
function buildGoal(x,dir){const g=new THREE.Group(),white=new THREE.MeshStandardMaterial({color:0xffffff,roughness:.4}),pg=new THREE.CylinderGeometry(.07,.07,2.44,10),bg=new THREE.CylinderGeometry(.07,.07,7.32,10),p1=new THREE.Mesh(pg,white),p2=p1.clone(),bar=new THREE.Mesh(bg,white);p1.position.set(0,1.22,-3.66);p2.position.set(0,1.22,3.66);bar.rotation.x=Math.PI/2;bar.position.set(0,2.44,0);g.add(p1,p2,bar);const net=new THREE.Mesh(new THREE.BoxGeometry(2.2,2.35,7.25,4,4,8),new THREE.MeshBasicMaterial({color:0xffffff,wireframe:true,transparent:true,opacity:.18}));net.position.set(dir*1.05,1.15,0);g.add(net);g.position.x=x;scene.add(g)}buildGoal(-52.5,-1);buildGoal(52.5,1);

function capsule(mat,r,len){const m=new THREE.Mesh(new THREE.CapsuleGeometry(r,Math.max(.05,len-r*2),7,12),mat);m.castShadow=true;return m}
function makeHuman(team='home',hero=false,gk=false){
  const kit=gk?(team==='home'?0x25c4ff:0xffaa28):(team==='home'?(hero?0xdfff4d:0x42b7e9):0xd83d4f),shorts=team==='home'?0x102b3a:0x6f1727;
  const skin=new THREE.MeshStandardMaterial({color:0x9f6a48,roughness:.76}),shirt=new THREE.MeshStandardMaterial({color:kit,roughness:.58}),shortsMat=new THREE.MeshStandardMaterial({color:gk?kit:shorts,roughness:.66}),sockMat=new THREE.MeshStandardMaterial({color:kit,roughness:.68}),bootMat=new THREE.MeshStandardMaterial({color:0x111111,roughness:.38}),hairMat=new THREE.MeshStandardMaterial({color:0x17110e,roughness:.9});
  const g=new THREE.Group();g.userData={parts:{},prev:new THREE.Vector3()};
  const torso=new THREE.Mesh(new THREE.CylinderGeometry(.29,.24,.82,14),shirt);torso.position.y=1.48;torso.scale.z=.72;torso.castShadow=true;g.add(torso);const chest=new THREE.Mesh(new THREE.SphereGeometry(.34,16,12),shirt);chest.scale.set(1,.55,.72);chest.position.y=1.67;chest.castShadow=true;g.add(chest);const waist=new THREE.Mesh(new THREE.CylinderGeometry(.22,.25,.26,12),shirt);waist.position.y=1.0;g.add(waist);const shortsMesh=new THREE.Mesh(new THREE.BoxGeometry(.56,.34,.42),shortsMat);shortsMesh.position.y=.82;shortsMesh.castShadow=true;g.add(shortsMesh);const neck=new THREE.Mesh(new THREE.CylinderGeometry(.095,.105,.17,10),skin);neck.position.y=2.04;g.add(neck);const head=new THREE.Mesh(new THREE.SphereGeometry(.205,20,16),skin);head.scale.set(.88,1.08,.9);head.position.y=2.25;head.castShadow=true;g.add(head);const hair=new THREE.Mesh(new THREE.SphereGeometry(.21,18,12,0,Math.PI*2,0,Math.PI*.48),hairMat);hair.position.y=2.32;g.add(hair);
  function arm(side){const shoulder=new THREE.Group();shoulder.position.set(side*.34,1.72,0);const upper=capsule(shirt,.075,.62);upper.position.y=-.28;shoulder.add(upper);const elbow=new THREE.Group();elbow.position.y=-.57;const lower=capsule(skin,.065,.58);lower.position.y=-.27;elbow.add(lower);shoulder.add(elbow);g.add(shoulder);return{shoulder,elbow}}
  function leg(side){const hip=new THREE.Group();hip.position.set(side*.145,.74,0);const upper=capsule(skin,.095,.78);upper.position.y=-.36;hip.add(upper);const knee=new THREE.Group();knee.position.y=-.73;const lower=capsule(sockMat,.078,.74);lower.position.y=-.34;knee.add(lower);const boot=new THREE.Mesh(new THREE.BoxGeometry(.18,.12,.39),bootMat);boot.position.set(0,-.73,.13);boot.rotation.x=-.08;boot.castShadow=true;knee.add(boot);hip.add(knee);g.add(hip);return{hip,knee}}
  const la=arm(-1),ra=arm(1),ll=leg(-1),rl=leg(1);g.userData.parts={la,ra,ll,rl,torso,chest,head};if(hero){const ring=new THREE.Mesh(new THREE.RingGeometry(.48,.61,40),new THREE.MeshBasicMaterial({color:0xffffff,side:THREE.DoubleSide,transparent:true,opacity:.92}));ring.rotation.x=-Math.PI/2;ring.position.y=.025;g.add(ring)}if(gk){const gloveMat=new THREE.MeshStandardMaterial({color:0xffffff});[-1,1].forEach(s=>{const glove=new THREE.Mesh(new THREE.BoxGeometry(.15,.11,.18),gloveMat);glove.position.set(s*.34,1.03,0);g.add(glove)})}g.scale.setScalar(hero?1.03:1);scene.add(g);return g;
}
const hero3D=makeHuman('home',true,false),mates3D=Array.from({length:9},()=>makeHuman('home')),foes3D=Array.from({length:10},()=>makeHuman('away')),homeGK=makeHuman('home',false,true),awayGK=makeHuman('away',false,true);const ball=new THREE.Mesh(new THREE.SphereGeometry(.22,20,16),new THREE.MeshStandardMaterial({color:0xffffff,roughness:.42}));ball.castShadow=true;scene.add(ball);
const homeFormation=[[-34,-24],[-34,-8],[-34,8],[-34,24],[-16,-20],[-14,0],[-16,20],[2,-20],[4,0]],awayFormation=[[34,-24],[34,-8],[34,8],[34,24],[16,-20],[14,0],[16,20],[-2,-20],[-4,0],[0,22]];function setFormation(){hero3D.position.set(-24,0,0);mates3D.forEach((o,i)=>o.position.set(homeFormation[i][0],0,homeFormation[i][1]));foes3D.forEach((o,i)=>o.position.set(awayFormation[i][0],0,awayFormation[i][1]));homeGK.position.set(-49,0,0);awayGK.position.set(49,0,0);ball.position.set(0,.22,0)}setFormation();

const aimGeom=new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(),new THREE.Vector3()]);const aimLine=new THREE.Line(aimGeom,new THREE.LineBasicMaterial({color:0xeaff76,transparent:true,opacity:.95}));aimLine.visible=false;scene.add(aimLine);const aimTarget=new THREE.Mesh(new THREE.TorusGeometry(.42,.055,8,28),new THREE.MeshBasicMaterial({color:0xeaff76,transparent:true,opacity:.95}));aimTarget.rotation.y=Math.PI/2;aimTarget.visible=false;scene.add(aimTarget);
function worldPos(p){return new THREE.Vector3((p.x/1100-.5)*FIELD_L,0,(p.y/620-.5)*FIELD_W)}
function stateYToZ(y){return(y/620-.5)*FIELD_W}
function syncHuman(obj,p,dt){if(!obj||!p)return;const target=worldPos(p),prev=obj.userData.prev,dx=target.x-prev.x,dz=target.z-prev.z,speed=Math.hypot(dx,dz)/Math.max(dt,.001);obj.position.x=target.x;obj.position.z=target.z;if(Math.hypot(dx,dz)>.006)obj.rotation.y=Math.atan2(dx,dz);const parts=obj.userData.parts,run=Math.min(1,speed/6.5),phase=performance.now()*.009*(1+run*.9),swing=Math.sin(phase)*.52*run;parts.ll.hip.rotation.x=swing;parts.rl.hip.rotation.x=-swing;parts.la.shoulder.rotation.x=-swing*.62;parts.ra.shoulder.rotation.x=swing*.62;parts.ll.knee.rotation.x=Math.max(0,-Math.sin(phase))*.36*run;parts.rl.knee.rotation.x=Math.max(0,Math.sin(phase))*.36*run;parts.torso.rotation.z=Math.sin(phase*2)*.014*run;parts.chest.rotation.y=Math.sin(phase)*.018*run;prev.copy(target)}
const clock=new THREE.Clock();
function cameraFollow(m){const hp=worldPos(m.player),mode=document.getElementById('cameraSelect')?.value||'Player Follow';let desired,look;if(mode==='Broadcast Lock'){desired=new THREE.Vector3(hp.x-2,27,hp.z+35);look=new THREE.Vector3(hp.x+10,0,hp.z)}else if(mode==='Shoulder'){desired=new THREE.Vector3(hp.x-5.8,3.25,hp.z+1.6);look=new THREE.Vector3(hp.x+8,1.15,hp.z)}else if(mode==='Pro Camera'){desired=new THREE.Vector3(hp.x-9.5,5.3,hp.z);look=new THREE.Vector3(hp.x+12,1.15,hp.z)}else{desired=new THREE.Vector3(hp.x-12.5,8.6,hp.z+1.2);look=new THREE.Vector3(hp.x+10,1,hp.z)}camera.position.lerp(desired,.075);camera.lookAt(look);const dir=new THREE.Vector3();camera.getWorldDirection(dir);dir.y=0;dir.normalize();bridge().cameraBasis={fx:dir.x,fz:dir.z,rx:-dir.z,rz:dir.x};}
function updateAim(m){const a=bridge().shotAim;if(!a?.active||m.ball?.owner!=='player'){aimLine.visible=false;aimTarget.visible=false;return;}const p=worldPos(m.player),targetY=310+(a.offset||0)*((372-248)*.43),target=new THREE.Vector3(52.2,.38,stateYToZ(targetY));aimTarget.position.copy(target);aimLine.visible=aimTarget.visible=true;const arr=aimLine.geometry.attributes.position.array;arr[0]=p.x;arr[1]=.35;arr[2]=p.z;arr[3]=target.x;arr[4]=target.y;arr[5]=target.z;aimLine.geometry.attributes.position.needsUpdate=true;aimLine.material.opacity=.45+.5*(a.power||.7);aimTarget.scale.setScalar(.8+.45*(a.power||.7));}
function resize(){const r=wrap.getBoundingClientRect();renderer.setSize(Math.max(1,r.width),Math.max(1,r.height),false);camera.aspect=Math.max(1,r.width)/Math.max(1,r.height);camera.updateProjectionMatrix()}new ResizeObserver(resize).observe(wrap);resize();
function animate(){requestAnimationFrame(animate);const dt=Math.min(.04,clock.getDelta()),m=getMatch();if(m){syncHuman(hero3D,m.player,dt);for(let i=0;i<mates3D.length;i++)syncHuman(mates3D[i],m.mates?.[i]||{x:190+(i%3)*110,y:90+Math.floor(i/3)*180},dt);for(let i=0;i<foes3D.length;i++)syncHuman(foes3D[i],m.foes?.[i]||{x:650+(i%4)*105,y:70+(i%5)*110},dt);syncHuman(homeGK,m.homeKeeper||{x:54,y:310},dt);syncHuman(awayGK,m.awayKeeper||m.keeper||{x:1046,y:310},dt);if(m.ball){const bp=worldPos(m.ball);ball.position.set(bp.x,.22,bp.z);ball.rotation.z+=((m.ball.vx||0)*dt)*.3;ball.rotation.x+=((m.ball.vy||0)*dt)*.3}cameraFollow(m);updateAim(m)}else{camera.position.lerp(new THREE.Vector3(-32,22,31),.03);camera.lookAt(0,0,0)}renderer.render(scene,camera)}animate();
const badge=document.createElement('div');badge.textContent='3D · 11 v 11';Object.assign(badge.style,{position:'absolute',left:'12px',top:'12px',zIndex:'6',padding:'6px 9px',borderRadius:'8px',background:'rgba(5,15,10,.7)',color:'#dfff4d',font:'800 10px system-ui',letterSpacing:'.12em',pointerEvents:'none'});wrap.appendChild(badge);
